networks:
  fraud-net:
    name: fraud-net
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  minio_data:
  clickhouse_data:
  airflow_db_data:
  airflow_logs:
  superset_home:

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: fraud_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: fraud_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_init:/docker-entrypoint-initdb.d
    networks: [fraud-net]

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks: [fraud-net]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks: [fraud-net]

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks: [fraud-net]

  spark-master:
    image: apache/spark:3.5.9-scala2.12-java17-python3-r-ubuntu
    container_name: spark-master
    entrypoint: ["/opt/spark/bin/spark-class"]
    command: ["org.apache.spark.deploy.master.Master"]
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./spark_jobs:/opt/spark/spark_jobs
    networks: [fraud-net]

  spark-worker:
    image: apache/spark:3.5.9-scala2.12-java17-python3-r-ubuntu
    container_name: spark-worker
    entrypoint: ["/opt/spark/bin/spark-class"]
    command: ["org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    environment:
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    depends_on: [spark-master]
    networks: [fraud-net]

  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks: [fraud-net]

  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: clickhouse
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}   
    ports:
      - "8123:8123"
      - "9004:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_init:/docker-entrypoint-initdb.d
    networks: [fraud-net]

  airflow-db:
    image: postgres:16
    container_name: airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    networks: [fraud-net]

  airflow-webserver:
    build: ./airflow
    container_name: airflow-webserver
    depends_on: [airflow-db]
    user: "0:0"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${AIRFLOW_DB_PASSWORD}@airflow-db/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}   
    ports:
      - "8081:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./spark_jobs:/opt/airflow/spark_jobs
      - ./dbt_project:/opt/airflow/dbt_project
      - airflow_logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock   
    command: >
      bash -c "airflow db init &&
      airflow users create --username admin --password ${AIRFLOW_ADMIN_PASSWORD} --firstname admin --lastname admin --role Admin --email admin@example.com || true &&
      airflow webserver"
    networks: [fraud-net]

  airflow-scheduler:
    build: ./airflow
    container_name: airflow-scheduler
    depends_on: [airflow-webserver]
    user: "0:0"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${AIRFLOW_DB_PASSWORD}@airflow-db/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}   
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./spark_jobs:/opt/airflow/spark_jobs
      - ./dbt_project:/opt/airflow/dbt_project
      - airflow_logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    command: airflow scheduler
    networks: [fraud-net]

  superset:
    image: apache/superset:6.1.0
    container_name: superset
    user: root
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    ports:
      - "8088:8088"
    volumes:
      - superset_home:/app/superset_home
    command: >
      bash -c "uv pip install --python /app/.venv/bin/python clickhouse-connect &&
      superset db upgrade &&
      (superset fab create-admin --username admin --password ${SUPERSET_ADMIN_PASSWORD} --firstname admin --lastname admin --email admin@example.com || true) &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088"
    networks: [fraud-net]