name: fraud_pipeline
version: "1.0.0"
config-version: 2

profile: fraud_pipeline

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  fraud_pipeline:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
